# Getting started

In [1]:
import numpy as np

from jigsaw import *
from jigsaw.default import *
from jigsaw.svg import *

In [2]:
# Choose only centered edge types, two sizes
edge_types = np.array([
    CENTERED_SMALL_MALE,
    CENTERED_MEDIUM_MALE,
])

# Automatically expand types to match combinations
edge_types = expand_edge_types(edge_types, opposite, flip)

# Show actual types
edge_names[edge_types]

array(['CENTERED_MEDIUM_MALE', 'CENTERED_MEDIUM_FEMALE',
       'CENTERED_SMALL_MALE', 'CENTERED_SMALL_FEMALE'], dtype='<U22')

In [3]:
# Generate grid
H, W = 3, 3
horizontal_edges, vertical_edges = sample_random_grid(H, W, edge_types)
horizontal_edges, vertical_edges

(array([[0, 6, 5, 0],
        [0, 4, 4, 0],
        [0, 5, 4, 0]]),
 array([[0, 0, 0],
        [6, 4, 6],
        [4, 4, 5],
        [0, 0, 0]]))

In [4]:
# Show it
display_grid(horizontal_edges, vertical_edges)

In [5]:
# Convert to list of pieces
pieces = grid_to_pieces(horizontal_edges, vertical_edges, opposite)
pieces

array([[[5, 0, 0, 6],
        [6, 0, 6, 4],
        [0, 0, 5, 6]],

       [[3, 5, 0, 4],
        [3, 3, 4, 4],
        [0, 5, 4, 5]],

       [[6, 3, 0, 0],
        [3, 3, 5, 0],
        [0, 6, 4, 0]]], dtype=uint8)

In [6]:
# Display all solutions
for h, v in iterate_solutions(H, W, pieces, opposite, flip, constraints="border"):
    display_grid(h, v)

In [7]:
# Display all unique solutions
for h, v in iterate_unique_solutions(H, W, pieces, opposite, flip, constraints="border"):
    display_grid(h, v)

In [8]:
# Shorthand
has_unique_solution(H, W, pieces, opposite, flip, constraints="border")

False